# Generated by Django 5.2.4 on 2025-08-02 21:47

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=2048)),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField()),
                ('public_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('content', models.FileField(upload_to=storage.models.file_path)),
            ],
        ),
    ]
