# Generated by Django 5.2.4 on 2025-08-02 23:35

import django.core.files.storage
import pathlib
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/userfiles/', location=pathlib.PurePosixPath('/home/lomik/MEGAsync/Projects/netology/diploma/backend/lomka_cloud/userfiles')), upload_to=storage.models.file_path),
        ),
    ]
