# Generated by Django 5.2.4 on 2025-08-05 10:25

import django.core.files.storage
import pathlib
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/userfiles/', location=pathlib.PurePosixPath('/userfiles')), upload_to=storage.models.file_path),
        ),
    ]
